print("about me")
print("name:alakam bhavya sree")
print("roll no:3207")
print("course:python")
print("phone:9032628875")
print("place:mpl")

print("about me")
print("name:alakam nandha kishore naidu")
print("roll no:3209")
print("course:python")
print("phone:9701102479")
print("place:cmp")